### ISSUE TITLE
play area manual property value from inspector ignored

### ISSUE THREAD

**Issue by syawqy** [quinnvoker/qurobullet#12]
Condition :
in bulletserver, I set play area mode = Manual
set Rect value to something
Play the scene and check the value again, the Rect value will be set to default (viewport size)

After I check multiple times, the Rect value in inspector are ignored when I play the scene
but if you set the value from a script, it will work

**Comment by quinnvoker** [comment]
Thanks for letting me know about this issue! 

I must've overlooked something when I added the manual play area mode. I'll investigate and keep you posted.

**Comment by quinnvoker** [comment]
Looks like I forgot to change a line in BulletServer's ready notification that causes the play area to update as if it's in Viewport mode, regardless of what the mode actually is. So whenever a BulletServer enters a scene and reaches ready, any manually inputted play area is overwritten with the viewport size.

This also explains why it still works properly if assigned via script.

I'll patch this as soon as I get home today.
