### ISSUE TITLE
Default values of BulletType rotation and rotation_degrees aren't simplified

### ISSUE THREAD

**Issue by efigi** [quinnvoker/qurobullet#19]
One thing I've noticed with the BulletType object is that its default value for rotation and rotation_degrees are these strange values. Is there a particular reason for this? Around 5% of the time that I run my build, the bullet rotation screws up without me changing anything. I'm thinking it has something to do with this

![image](https://user-images.githubusercontent.com/3532195/95432634-7eefad80-0981-11eb-8047-093a6585d1d7.png)

I'll try making a pull request for this later, I'll make their default values 0

**Comment by quinnvoker** [comment]
No, that's not intentional behaviour! Looking at bullet_type.cpp, looks like I just forgot to assign a default value to `rotation` in the constructor. Should be a quick and easy fix. I should be able to update that this weekend if you haven't already fixed it yourself haha
