### ISSUE TITLE
No method to get array of bullets

### ISSUE THREAD

**Issue by remtaine** [quinnvoker/qurobullet#21]
A lot of bullet hells clear their bullets if the player is hit. The current BulletServer has a clear_bullets() function for this, but it just leaves them all without a trace. I was thinking of putting particles where they were before clearing the bullets. Maybe it'd be good to add access to the bullets array, or at least an array of their positions?

**Comment by quinnvoker** [comment]
Seems like a reasonable feature request! I've got the next few days free so I'll experiment with a few approaches.

**Comment by quinnvoker** [comment]
I added a couple of accessor functions to BulletServer to accommodate this functionality. Check out the PR for more info!
