### ISSUE TITLE
Have Z-index for Bullets created by BulletSpawner

### ISSUE THREAD

**Issue by remtaine** [quinnvoker/qurobullet#25]
Hello! When making bullet hell's, I noticed that the important bullets get covered by the less important. An example is here, where the enemy's bullets cover the player's. Ideally, the player's bullets are seen more.

![image](https://user-images.githubusercontent.com/3532195/101758406-42703780-3b13-11eb-80f8-fb97c153392d.png)

This can be solved if BulletSpawner or BulletType had an attached Z-index for the bullets. That way, it's easy to emphasize the more important bullets.
 
I think there's a way to do this through having multiple BulletServers then arranging them there, but I think each BulletSpawner having their own Z-index attached to their bullets would be better 😁

What do you think?

Edit: taking a quick look at the code, would adding z to this line work? I'll probably try it out later:

`VS::get_singleton()->canvas_item_set_draw_index(bullet->get_ci_rid(), i + (z * 10000));`

**Comment by quinnvoker** [comment]
Actually, if you look at your example screenshot, even there the bullets aren't set on separate layers, the top right player bullet is actually overlapping the enemy bullet directly above it. qurobullet orders all its bullets z levels by creation time to make sure patterns look nice, and I'd imagine this screenshot is using a similar setup.

If multiple layers are required in a game to distinguish player bullets from enemy bullets, my preferred solution there would be to just add another BulletServer instance to your scene, so the player uses one server, and the enemies use another. Bullets are stored as children of the BulletServer, so their layering will honor the ordering of the BulletServers in the scene tree.

**Comment by remtaine** [comment]
Got it! Thank you 😁

**Comment by quinnvoker** [comment]
Oops I read your original comment wrong, and just realised that you DIDN'T want the enemy bullets to cover player bullets, and I'm now realizing that the screenshot was probably your game with qurobullet and not some other system... At least the same solution applies lol 😅

**Comment by remtaine** [comment]
Yup! It's my game using this module 😁 I'll go set up two BulletServers so the player bullets are always over the enemy bullets 😄
