### ISSUE TITLE
It does works... 👍 

### ISSUE THREAD

**Issue by ciso507** [quinnvoker/qurobullet#35]
I just recently compiled godot3.44 and then i added the qurobullet.... module as ur docs says, then i receive an error, i think your module is not updated to 3.44 version :/ lot of errors

**Comment by quinnvoker** [comment]
Which branch of qurobullet were you using? The `main` branch (used by default when cloning) is a currently unfinished version for Godot 4. `godot-3.x` is the branch for Godot 3.

If you used `main`, try going into the qurobullet module directory and changing the branch with `git switch godot-3.x` and recompiling.

If you were already using that branch (or changing to it doesn't resolve your problem), reply here and I'll set aside some time to update the module for compatibility with 3.44 this week.

**Comment by ciso507** [comment]
thanks for your quick response, i apreciate it alot, your qurobullet module is one of the most epics out there that ive seen :D, ill try just now to git switch inside the qurobullet folder

**Comment by quinnvoker** [comment]
I actually just added that line to the docs today! You're not the first person to run into that problem, and probably not the last either, so I figured I'd try and help people avoid it in the future. Glad it seems to be working for you now, though! 

Have fun making your game!

**Comment by ciso507** [comment]
i did built this time, but when i search for bulletenvironment or bullet nodes it doesnt appear on my godot

**Comment by ciso507** [comment]
[](
<img width="2343" alt="Screen Shot 2022-06-09 at 3 42 33 AM" src="https://user-images.githubusercontent.com/77065120/172804902-cc41f6b9-a3fe-40e6-813d-321ef50bcf6d.png">
url).  the bulletserver doesnt show up or the bulletspawner

**Comment by quinnvoker** [comment]
Hey thanks for the screenshot! Just tried compiling it for myself and am seeing the same issue. I'll do my best to get things compatible with the most recent Godot 3.x and get back to you.

**Comment by quinnvoker** [comment]
In order to resolve common issues with compilation, I've decided to experiment with making my own builds of godot with qurobullet installed for distribution! I've tested builds on Linux and Windows and it seems to work as normal on those platforms, but I haven't tested on MacOS yet. I do have a build for it though! If you could try it and let me know if it works for you, that would be a huge help!

https://github.com/quinnvoker/godot-qurobullet/suites/6894967715/artifacts/267372895

**Comment by ciso507** [comment]
Thanks a lot i highly apreciate it :D

**Comment by quinnvoker** [comment]
I've put together some cross-platform pre-built Godot binaries with qurobullet included in them over here: https://github.com/quinnvoker/godot-qurobullet/releases/tag/v1.1-godot-3.4.4

I haven't had an opportunity to check the MacOS builds yet, but Windows and Linux builds appear to be working as expected. Try the `macos-editor` package from there and let me know if BulletServer/BulletSpawner nodes show up in your search when using it.

This is my first time trying to provide public builds of Godot with qurobullet in it, so I hope this works well for you!

**Comment by ciso507** [comment]
this time i was able to set it up thanks to you :D very much
